version: '3'
services:
  app:
    container_name: voodoo-coaching
    
    command: npm run dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      # - .:/app
      - /voodoo-docker
      - /voodoo-docker/node_modules/
      
      